services:

  mysql:
    image: mysql:9.2
    restart: always
    container_name: mysqldb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=user_manager_db
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 5s

  server:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    container_name: server
    links:
      - mysql:mysql
    hostname: server
    ports:
      - 6868:8080
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=null
      - DB_NAME=user_manager_db
      - DB_PORT=3306
    networks:
      - app_network

  client:
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./client/.env:/app/.env
      - ./client/public:/app/public
      - ./client/src:/app/src
    links:
      - server:server
    hostname: client

volumes:
  dbdata:

networks:
  app_network:
    driver: bridge